services:
  securechat.server:
    image: securechat-server
    build:
      context: .
      dockerfile: SecureChat.Server/Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - securechat.database
      - kafka

  securechat.client:
    image: securechat-client
    build:
      context: .
      dockerfile: SecureChat.Client/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - securechat.server

  securechat.database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: securechatdb
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2185:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9097:9092"

volumes:
  postgres_data: