networks:
  securechat_network:
    name: securechatsolution_securechat_network
    driver: bridge

services:
  securechat.server:
    networks:
      - securechat_network
    image: securechat-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5078/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      KAFKA_BOOTSTRAP_SERVERS: localhost:9097
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: password
    volumes:
      - aspnet-data-protection-keys:/root/.aspnet/DataProtection-Keys
    build:
      context: .
      dockerfile: SecureChat.Server/Dockerfile
    ports:
      - "5001:5000"
      - "5002:5001"
    depends_on:
      - securechat.database
      - kafka
      - rabbitmq

  frontend:
    image: frontend
    build:
      context: .  # Путь к вашему React-проекту
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"  # Прокси на 80 порт внутри контейнера для Nginx
    depends_on:
      - securechat.server
    networks:
      - securechat_network

  securechat.database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: securechatdb
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - securechat_network
  
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"  # AMQP порт
      - "15672:15672"  # Web-интерфейс
    networks:
      - securechat_network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2185:2181"
    networks:
      - securechat_network

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9097
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - "9097:9092"
    networks:
      - securechat_network
    
volumes:
  postgres_data:
  aspnet-data-protection-keys: